### ISSUE TITLE
可以函数式地调出confirm么

### ISSUE THREAD

**Issue by visonforcoding** [Wildtyto/Alert7.js#1]
可以简便地用函数式方法调出confirm么？期待回复。

**Comment by CodyWildtyto** [comment]
謝謝你的建議，我會在下個版本追加可快速調用confirm的靜態方法。

**Comment by CodyWildtyto** [comment]
現在可調用`Alert7.confirm`方法快速實現confirm：

```
Alert7.confirm( _titleStr, _messageStr, _btn1Str, _btn1Handler, _btn2Str, _btn2Handler)
```

**Comment by visonforcoding** [comment]
@Wildtyto  感謝你的工作，非常好用。UI非常漂亮，加油，如果能支持無title的alert.和 text、password 類型prompt，那就完美了，實現了ios所有的彈出效果了！！

**Comment by CodyWildtyto** [comment]
謝謝，我會再繼續優化更多實用性。
